name: leporello

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.leporello.rule=Host(`leporello.app`)"
      - "traefik.http.routers.leporello.entrypoints=websecure"
      - "traefik.http.routers.leporello.tls.certresolver=myresolver"
      - "traefik.http.services.leporello.loadbalancer.server.port=3000"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    restart: "no"
    volumes:
      - ./data:/app/data
    profiles:
      - scrape

networks:
  gateway:
    external: true
